baseURL = 'https://brunozc.github.io'
languageCode = 'en-us'
title = 'Bruno Zuada Coelho'
theme = 'gokarna'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/pages/about_me"
    weight = 1  # Weights are used to determine the ordering

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/pages/research"
    weight = 2

  [[menu.main]]
    identifier = "software"
    name = "Software"
    url = "/pages/software"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/pages/contact"
    weight = 4


[params]
  # URL for the avatar on homepage
  avatarURL = "/me.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  description = "I am a geotechnical engineer with an interest in dynamics, numerical modelling and AI."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = ""

  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/bruno-zuada-coelho/"},
    {name = "researchgate", url = "https://www.researchgate.net/profile/Bruno-Zuada-Coelho"},
    {name = "googlescholar", url = "https://scholar.google.nl/citations?user=AQkEIFIAAAAJ&hl=en"},
    ]

  # Footer text